### ISSUE TITLE
Relegating C+= source code to a file is misogynistic.

### ISSUE THREAD

**Issue by JacobMisirian** [ErisBlastar/cplusequality#12]
Hai! As I was reading through your repo I noticed that source code written in C+= has to be in a single source file. Since C+= is for female empowerment, the restriction of it into one territory is patriarchal and deeply problematic. I propose a system where source code is free to choose where it wants to be, instead of gerrymandered into a monogamous I/O operation.

**Comment by Trojaner25** [comment]
:+1:

**Comment by ErisBlastar** [comment]
This has caused a 121 year delay in the programming to fix this issue. I think my great-great-granddaughter will be able to fix it some day. That is about the time society and culture catches up with social justice and feminism as females and transgender females find a way to reproduce without a male or transgender female. By that time I'll be a brain in a jar, waiting to get a brand new robotic body to put my brain into. FrankenEris I'll become and see then how to fix it.
