### ISSUE TITLE
I'm extremely triggered

### ISSUE THREAD

**Issue by activedecay** [ErisBlastar/cplusequality#14]
I can't quite place my finger on it, but this repo is offensive to someone. I personally love it, and I'm overjoyed. :tada: :1st_place_medal:  

Also, I think the wall just got 10 feet higher. Bravo. What's even in this repo? I can't stop laughing long enough to clone it.

**Comment by ErisBlastar** [comment]
I am a Discordian Humanist, and I am trying to fix this repo that was censored and banned on other Git sites. This is the attempt at a Feminist programming language C++ Equality, written by feminists for feminists and no mainsplaining or manspreading or whatever. All White Knights will be put into the Friend Zone, all Cucks will be made effeminate. There are now more different genders than Baskin Robbins has ice cream flavors.
