### ISSUE TITLE
This is sarkasm right?

### ISSUE THREAD

**Issue by nshtg** [ErisBlastar/cplusequality#15]
Right?

**Comment by dodekeract** [comment]
No, we are genuine feminists. How else would we be able to come to such... intelligent conclusions?

**Comment by activedecay** [comment]
Such robust feminist arguments.

**Comment by nshtg** [comment]
Are you, by any chance, a priviliged cis male rapist that enjoys triggering feminists? shame on you!

**Comment by ErisBlastar** [comment]
Did someone assume our genders? How can we not be feminists when this is a feminist programming project? I think I need a safe space for the next few years or so, until I can get back to this project.

**Comment by ErisBlastar** [comment]
No privileged cis male rapists that enjoys triggering feminists here. We
are all marginalized people of color and noncis non-binary people with a
different gender. We like to hang out on Tumblr and whine and complain
about how bad we got it and how the world has to change to suit us. Come
sit by the campfire and tell us your tales of triggering in Sarkastic
ballads. There is racism, sexism, homophobia everywhere and you have to
point it out to people as they are too stupid to notice it!

Well I have to get back to my real job as a cashier at Diary Queen. Nice
talking to you all.

**Comment by activedecay** [comment]
Yeah, we each have a different gender. Mine is xher, pronounced sure. It's a homonym, and I'm proud to say it's a pro-homo pronoun.
