### ISSUE TITLE
This is shit. Pointless. Worthless. Meaningless shit.

### ISSUE THREAD

**Issue by Sebine** [ErisBlastar/cplusequality#3]
Remove it.

**Comment by Vultour** [comment]
@Sebine still more useful than you

**Comment by prateekkarki** [comment]
You're wrong. Its not just shit. If shit could fuck and make a shit baby and that shit baby takes a shit, this is what would come out of the shit baby's ass.

**Comment by Mange** [comment]
Of course someone named "Patriarchy" (misspelled) would be critical of this
progressive beacon in the darkness of the internets. (◡‿◡✿)

tors 15 okt. 2015 19:37 prateekkarki <notifications@github.com> skrev:

**Comment by ErisBlastar** [comment]
I fail to see the programming issues here. There is no bug reported, just some political issues that don't belong on Github. This is offtopic and thus will be closed as unproductive.

**Comment by wingy** [comment]
no, this is patrick
