### ISSUE TITLE
This will not be complete with SJWs sabotaging the issues

### ISSUE THREAD

**Issue by cable2600c** [ErisBlastar/cplusequality#34]
Being triggered is not a software issue. Go seek professional help.

**Comment by activedecay** [comment]
If it's not a software issue then why open an issue? 🤔 Is there some way we can make it into a software issue?

**Comment by cable2600c** [comment]
I wanted to get everyone's attention on it. We can make it into a software issue by adding a trigger catcher into the code to avoid people getting triggered. Based on AI Software Psychology.
