### ISSUE TITLE
This shit IS the issue.

### ISSUE THREAD

**Issue by Sebine** [ErisBlastar/cplusequality#4]
This isn't Code

This isn't Equality

This is Feminazi Propaganda Bullshit

WIMMINZ B NEEDIN DERE OWN KODE MUH NIGGA

No, you can fuck yourself and use the same code everyone else uses.

**Comment by fche** [comment]
Please look up Poe's Law.

**Comment by Mange** [comment]
Issue tag for "Poe's Law"? It would be a nice thing to have.

lör 17 okt. 2015 22:45 Frank Ch. Eigler <notifications@github.com> skrev:

**Comment by Vultour** [comment]
@Sebine please use the issue tracker to report any bugs or otherwise code related problems, not for pushing your political views. This is after all GitHub, not a political discussion forum. Thank you.

**Comment by Qix-** [comment]
Someone needs a refresher on the definition of *satire*.

**Comment by ErisBlastar** [comment]
This is satire and sarcasm and other forms of humor. 

Feminists have source code raped me over this, I've been triggered.
