### ISSUE TITLE
The example links are not working

### ISSUE THREAD

**Issue by rfree** [ErisBlastar/cplusequality#9]
The example links are not working

**Comment by rfree** [comment]
to be exact: entire
https://bitbucket.org/FeministSoftwareFoundation/c-plus-equality
projects is blocked there.

Seems the Cultural Marxism virus did spread to bitbucket as well. 
@ErisBlastar will you move the code and fix the examples links in README.md?

**Comment by ErisBlastar** [comment]
I fixed the links but had to remove sieve example because I don't have it. I didn't make this project I just mirrored it because I knew it would get deleted on Bitbucket so I can't take credit for it.
